apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    name: jenkins-service
    app: myapp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008
  selector:
    name: jenkins-pod
    app: myapp
