apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkins-pod
      app: myapp
  template:
    metadata:
      name: jenkins-pod
      labels:
        name: jenkins-pod
        app: myapp
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
